/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.artlist_creator.dev;

import com.artlist_creator.dev.model.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Camer
 */
public class QuestionPanel extends javax.swing.JPanel implements ActionListener {
    
    List<JComponent> ansComp = new ArrayList<>();
    Question question;
    String[] answers;
    int point = 0;

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel(Question ques) {
        initComponents();
        question = ques;
        q_content.setText(ques.getContent());
        ButtonGroup onlyOneChoice = new ButtonGroup();
        int size = (int) ques.getAnswers().stream().filter(Answer::isCorrect).count(), count = 0;
        answers = new String[size];
        for(int i = 0, n = ques.getAnswers().size() ; i < n; i ++)
        {
            AbstractButton answerSections;
            if(ques.isMultipleChoice())
            {
                answerSections = new JCheckBox(ques.getAnswers().get(i).getContent());
            }
            else
            {
                answerSections = new JRadioButton(ques.getAnswers().get(i).getContent());
                onlyOneChoice.add(answerSections);
            }
            answerSections.addActionListener(this);
            ansComp.add(answerSections);
            q_choices.add(answerSections);
            if(ques.getAnswers().get(i).isCorrect())
            {
                answers[count]= ques.getAnswers().get(i).getContent();
                count++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q_content = new javax.swing.JLabel();
        q_choices = new javax.swing.JPanel();

        q_content.setText("Question contents");

        q_choices.setLayout(new javax.swing.BoxLayout(q_choices, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q_content, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(q_choices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(q_content, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q_choices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel q_choices;
    private javax.swing.JLabel q_content;

    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        if(actionEvent.getSource() instanceof AbstractButton)
        {
            AbstractButton btn = (AbstractButton) actionEvent.getSource();
            if(btn.isSelected() && isTrue(btn))
            {
                point ++;
            }
            if(!btn.isSelected() && isTrue(btn))
            {
                point --;
            }
        }
    }

    private boolean isTrue(AbstractButton k)
    {
        String content = k.getText();
        for(String ans : answers)
        {
            if(ans.equals(content))
            {
                return true ;
            }
        }
        return false;
    }

    public int getScore()
    {
        return point;
    }
    // End of variables declaration//GEN-END:variables
}
