/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.artlist_creator.dev;

import com.artlist_creator.dev.model.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JRadioButton;

/**
 *
 * @author Camer
 */
public class QuestionPanel extends javax.swing.JPanel {
    
    List<JComponent> ansComp = new ArrayList<>();

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel(Question ques) {
        initComponents();
        q_choices.setLayout(new javax.swing.BoxLayout(q_choices, javax.swing.BoxLayout.Y_AXIS));

        q_content.setText(ques.getContent());
        ButtonGroup choices = new ButtonGroup();
        for(int i = 0, n = ques.getAnswers().size() ; i < n; i ++)
        {
            AbstractButton ansBoxs;
            if(ques.isMultipleChoice())
            {
                ansBoxs = new JCheckBox(ques.getAnswers().get(i).getContent());
                
            }
            else
            {
                ansBoxs = new JRadioButton(ques.getAnswers().get(i).getContent());
                choices.add(ansBoxs);
            }
            ansComp.add(ansBoxs);
            q_choices.add(ansBoxs);  
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q_content = new javax.swing.JLabel();
        q_choices = new javax.swing.JPanel();

        q_content.setText("Question contents");

        q_choices.setLayout(new javax.swing.BoxLayout(q_choices, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q_content, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(q_choices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(q_content, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q_choices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel q_choices;
    private javax.swing.JLabel q_content;
    // End of variables declaration//GEN-END:variables
}
