/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Author;
import java.awt.Component;
import java.sql.Date;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author Camer
 */
public class AuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorPanel
     */
    Author author;
    Canvas layerCanvas;
    Component box;

    public AuthorPanel(Canvas parent) {
        initComponents();
        author = new Author();
        author.setGender("M");
        layerCanvas = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderChoice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        dobTxt = new javax.swing.JTextField();
        insTxt = new javax.swing.JTextField();
        maleRad = new javax.swing.JRadioButton();
        feRad = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(330, 240));

        jLabel1.setText("ID: ");

        jLabel2.setText("DOB: ");

        jLabel3.setText("Name: ");

        jLabel4.setText("Institution: ");

        jLabel5.setText("Gender:  ");

        delButton.setText("Delete");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTxtFocusLost(evt);
            }
        });

        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFocusLost(evt);
            }
        });

        dobTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobTxtFocusLost(evt);
            }
        });

        insTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                insTxtFocusLost(evt);
            }
        });

        genderChoice.add(maleRad);
        maleRad.setSelected(true);
        maleRad.setText("Male");
        maleRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadActionPerformed(evt);
            }
        });

        genderChoice.add(feRad);
        feRad.setText("Female");
        feRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feRadActionPerformed(evt);
            }
        });

        addButton.setText("More");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feRad)
                                .addGap(0, 80, Short.MAX_VALUE))
                            .addComponent(nameTxt)
                            .addComponent(dobTxt)
                            .addComponent(idTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(insTxt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(insTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maleRad)
                    .addComponent(feRad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delButton)
                    .addComponent(addButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void feRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feRadActionPerformed
        // TODO add your handling code here:
        author.setGender("F");
    }//GEN-LAST:event_feRadActionPerformed

    private void maleRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadActionPerformed
        // TODO add your handling code here:
        author.setGender("M");
    }//GEN-LAST:event_maleRadActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        if(layerCanvas.tiles.size() == 1) return;
        layerCanvas.body.remove(this);
        layerCanvas.tiles.remove(this);
        layerCanvas.pack();
    }//GEN-LAST:event_delButtonActionPerformed

    private void idTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusLost
        // TODO add your handling code here:
        author.setID(idTxt.getText());
    }//GEN-LAST:event_idTxtFocusLost

    private void nameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusLost
        // TODO add your handling code here:
        author.setName(nameTxt.getText());
    }//GEN-LAST:event_nameTxtFocusLost

    private void insTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insTxtFocusLost
        // TODO add your handling code here:
        author.setInstituton(insTxt.getText());
    }//GEN-LAST:event_insTxtFocusLost

    private void dobTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobTxtFocusLost
        // TODO add your handling code here:
        //        // TODO add your handling code here:
        if (!Canvas.isDateValid(dobTxt.getText())) {
            JOptionPane.showMessageDialog(dobTxt, "Beware: you wrote an invalid date");
            dobTxt.setText(null);
        } else {
            try {
                java.util.Date parseDate = Canvas.df.parse(dobTxt.getText());
                author.setDob(new Date(parseDate.getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(AuthorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_dobTxtFocusLost

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        AuthorPanel newAu =  new AuthorPanel(layerCanvas);
        layerCanvas.tiles.add(newAu);
        layerCanvas.body.add(newAu);
        layerCanvas.pack();
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JRadioButton feRad;
    private javax.swing.ButtonGroup genderChoice;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField insTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton maleRad;
    private javax.swing.JTextField nameTxt;
    // End of variables declaration//GEN-END:variables
}
